### PR TITLE
Naming, headers, and declaration changes to match style guide

### PR DESCRIPTION
**Pull request by bsutherland333**
I did some cleaning and refactoring of ROSplane:
- Matched all class, enum, struct, member variables, and function names to match ROSflight style guide
- Organized includes to match ROSflight style guide and removed unused ones
- Removed various unnecessary declarations/initializations
- Fixed a wild bug where a namespace was being opened and closed in separate files

### CODE REVIEW

**Review by iandareid — APPROVED** [review]
Looks thorough!

**Comment by bsutherland333** [comment]
@iandareid did you want me to merge this in now, or wait?

**Comment by iandareid** [comment]
I think perhaps we should wait. I know that the refactor of the EKF may create large conflicts. What do you think?

**Comment by bsutherland333** [comment]
We can wait. I'll let you merge it in when you'd like. But I don't want to do this twice xD.

**Comment by bsutherland333** [comment]
@iandareid Is the EKF refactoring on a branch somewhere? Maybe what we should do is I can deconflict the EKF changes as they are now and then merge the refactoring in before.

**Comment by bsutherland333** [comment]
Ok I got a plan for deconfliction, just let me know when the EKF refactoring is pushed and I'll update it 😎

**Pull request merged**
